on:
  workflow_dispatch:
  create:
  release:
    types: [created]

name: build libobjc
jobs:
  build:
    name: build libobjc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get cosmos-sdk
        run: |
          cd
          mkdir -p .cosmo
          cd .cosmo
          wget https://cosmo.zip/pub/cosmocc/cosmocc-3.1.3.zip
          wget https://github.com/codehz/superconfigure/releases/download/main/aarch64-gcc.zip
          wget https://github.com/codehz/superconfigure/releases/download/main/x86_64-gcc.zip
          unzip -o '*.zip'
          rm *.zip
      - name: Fix ape
        run: |
          curl https://justine.lol/ape.elf >ape
          chmod +x ape
          mv ape /usr/bin/ape
          echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register
      - name: Run make
        run: make && tree